### ISSUE TITLE
'x' is off in community plugins search box

### ISSUE THREAD

**Issue by ryanpcmcquen** [chad-bennett/al-dente-obsidian-theme#1]
Windows 10 x64, Obsidian 0.12.3:
![2021-05-28 14_29_56-LaRok - Obsidian v0 12 3](https://user-images.githubusercontent.com/772937/120043730-558f9a80-bfc1-11eb-8970-457530e7f530.png)

**Comment by chad-bennett** [comment]
fixed. you can download and update from github. not sure how long it takes to update through the community themes page.

**Comment by ryanpcmcquen** [comment]
Thank you!
