### ISSUE TITLE
Horizontal split panes not resizable

### ISSUE THREAD

**Issue by parkerbennett** [chad-bennett/al-dente-obsidian-theme#2]
Obsidian 0.12.3, Mac OS X 11.4 on M1 MacBook Pro:
![screenshot-al-dente-no-horizontal-pane-resizing](https://user-images.githubusercontent.com/316268/120431616-92df8980-c32d-11eb-87cf-e93b9823a2d6.jpg)

**Comment by chad-bennett** [comment]
fixed. you can download and update from github. not sure how long it takes to update through the community themes page.
