### ISSUE TITLE
404-ing

### ISSUE THREAD

**Issue by ryanpcmcquen** [chad-bennett/al-dente-obsidian-theme#3]
Looks like the path to the CSS file was changed, but Obsidian is expecting `obsidian.css`, so installing the theme now fails.

<img width="1932" alt="Screen Shot 2021-06-02 at 10 58 13 AM" src="https://user-images.githubusercontent.com/772937/120529613-842abe00-c391-11eb-9a21-49e19f3cb572.png">

**Comment by chad-bennett** [comment]
fixed!

i made a copy of the theme and renamed it to obsidian.css and it now works in the community themes again.
