### ISSUE TITLE
Tables are hard to read

### ISSUE THREAD

**Issue by ryanpcmcquen** [chad-bennett/al-dente-obsidian-theme#4]
I think this is only an issue when links exist in the tables:
<img width="418" alt="Screen Shot 2021-06-11 at 9 56 39 AM" src="https://user-images.githubusercontent.com/772937/121723813-d9568600-ca9b-11eb-992e-752ff3abc196.png">

**Comment by chad-bennett** [comment]
just updated with tweaked table display settings. let me know if it works for you.
